[package]
name = "get-contracts-from-buckets"
version = "0.1.0"
edition = "2024"

[dependencies]
stellar-xdr = "23.0.0"
reqwest = { version = "0.11", features = ["json", "gzip"] }
tokio = { version = "1", features = ["full"] }
hex = "0.4"
flate2 = "1.0"
human_bytes = "0.4"
