[package]
name = "extract-meta"
version = "0.1.0"
edition = "2021"

[dependencies]
soroban-meta = { version = "23.0.3", git = "https://github.com/stellar/rs-soroban-sdk", branch = "release/v23.0.3" }
stellar-xdr = { version = "23.0.0", features = ["serde"] }
serde_json = "1.0"
